version: '3'

services:
  web: 
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/workspace
      - gem_path:/gems
    env_file:
      - .env/development/database 
      - .env/development/web 
    depends_on:
      - database
  
  database:
    image: postgres 
    env_file:
      - .env/development/database 
    volumes:
      - db_data:/var/lib/postgresql/data 
    


volumes:
  db_data:
  gem_path: