name: "Changelog"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run changelog CI
        uses: saadmk11/changelog-ci@v1.1.0
        with:
          changlog_filename: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Changelog Output
        run: |
          echo "${{ steps.changelog-ci.outputs.changelog }}"
          echo "${{ steps.changelog-ci.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY
