name: test action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: name current branch
      run: |
        git branch
    - name: "Build Changelog"
    - id: build_changelog
    - uses: mikepenz/release-changelog-builder-action@{latest-release}
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: create file
      run: | 
        ls -a
        touch ./test.txt
        echo 'hello world' >> ./test.txt
        sudo apt-get update && sudo apt-get upgrade -y
        
