name: test action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: name current branch
      run: |
        git branch
    - name: "Build Changelog"
    - uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
    - name: create file
      run: | 
        ls -a
        touch ./test.txt
        echo 'hello world' >> ./test.txt
        sudo apt-get update && sudo apt-get upgrade -y
        
