name: Test Build

on: [push]
  
jobs:
  build-changelog:
  
    runs-on: ubuntu-latest  
  
    steps:
    - name: create text file
      run: | 
        touch ${PWD}/test.txt
        echo 'hello world' >> ${PWD}/test.txt
