name: test action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: create file
      run: | 
        ls -a
        touch ./test.txt
        echo 'hello world' >> ./test.txt
        sudo apt-get update
        
